ktor:
  development: false
  application:
    modules:
      - com.batr.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/face-recognition"
  user: postgres
  password: $DB_PASSWORD
googleapi:
  auth:
    google-client-secret: $GOOGLE_CLIENT_SECRET
    google-client-id: $GOOGLE_CLIENT_ID
auth:
  token-life-time-ms: 3600000
  long-token-life-time-ms: 604800000
log:
  currentLogAmount: 200
settings:
  path: "/home/danil/testweb"
  file: "settings.json"
python:
  bearer-token: $PY_TOKEN