hash.argon2.memory=15360
hash.argon2.iterations=4
hash.argon2.length=64
hash.argon2.parallelism=4
hash.argon2.type=id
global.salt.length=32
hash.argon2.version=19

global.pepper=ON8h(*u4j9023ufdsioo()UhvuIOJjvf